[package]
name = "engine_comm"
version = "0.1.0"
authors = ["Mateusz Górski <gorski.mateusz@protonmail.ch>"]
description = "WASM execution engine for CasperLabs smart contracts"
license = "Apache-2.0"

[dependencies]
protobuf = "2"
grpc = "0.6.1"
futures = "0.1.8"
futures-cpupool = "0.1.8"
execution-engine = { path = "../engine" }
clap = "2.32.0"
storage = { path = "../storage" }
common = { path = "../common", package = "casperlabs-contract-ffi" }

[build-dependencies]
protoc-rust-grpc = "0.6.1"

[[bin]]
name = "engine-grpc-server"
path = "src/main.rs"


[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
engine_comm = { path = "/usr/bin/engine_comm" }
