[package]
name = "engine_comm"
version = "0.1.0"
authors = ["Mateusz Górski <gorski.mateusz@protonmail.ch>"]

[dependencies]
protobuf = "2"
grpc = "0.6.1"
futures = "0.1.8"
futures-cpupool = "0.1.8"
execution-engine = { path = "../engine" }
clap = "2.32.0"
storage = { path = "../storage" }
common = { path = "../common", package = "casperlabs-contract-ffi" }

[build-dependencies]
protoc-rust-grpc = "0.6.1"

[[bin]]
name = "engine-grpc-server"
path = "src/main.rs"
