[package]
name = "erc20-logic"
version = "0.1.0"
authors = ["Maciej Zieliński <maciej@casperlabs.io>"]
edition = "2018"

[lib]
name = "erc20_logic"
doctest = false

[features]
default = ["use_std"]
use_std = []