[package]
name = "standard-payment"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract/std"]
lib = []

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
