[package]
name = "bonding-call"
version = "0.1.0"
authors = ["Srinivas Reddy Thatiparthy <srini@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
contract-ffi = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }
