[package]
name = "simple-transfer"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
