[package]
name = "test-transfer-to-account-2-call"
version = "0.1.0"
authors = ["Joe Sacher <joe@casperlabs.io>"]
edition = "2018"

[lib]
name = "test_transfer_to_account_2_call"
crate-type = ["cdylib"]

[features]
default = []
std = ["cl_std/std"]

[dependencies]
cl_std = { path = "../../../../execution-engine/common/", package = "casperlabs-contract-ffi" }
