[package]
name = "pos"
version = "0.1.0"
authors = ["Andreas Fackler <andreas@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]
bench = false
doctest = false

[features]
default = []
std = ["contract-ffi/std"]
lib = []

[dependencies]
base16 = { version = "0.2", default-features = false }
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
