[package]
name = "pos"
version = "0.1.0"
authors = ["Andreas Fackler <andreas@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]
bench = false
doctest = false

[features]
default = []
std = ["contract/std"]
lib = []

[dependencies]
base16 = { version = "0.2.1", default-features = false }
contract = { path = "../../../contract", package = "casperlabs-contract" }
