[package]
name = "named-purse-payment"
version = "0.1.0"
authors = ["Ed Hastings <ed@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
