[package]
name = "casperlabs-engine-test-support"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"

[dependencies]
contract = { path = "../contract", package = "casperlabs-contract" }
engine-core = { path = "../engine-core", package = "casperlabs-engine-core" }
engine-grpc-server = { path = "../engine-grpc-server", package = "casperlabs-engine-grpc-server" }
engine-shared = { path = "../engine-shared", package = "casperlabs-engine-shared" }
engine-storage = { path = "../engine-storage", package = "casperlabs-engine-storage" }
engine-wasm-prep = { path = "../engine-wasm-prep", package = "casperlabs-engine-wasm-prep" }
grpc = "0.6.1"
lazy_static = "1"
lmdb = "0.8.0"
num-traits = "0.2.10"
rand = "0.7.2"
protobuf = "=2.8"

[features]
use-as-wasm = []
