[package]
name = "create-test-node-shared"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[features]
default = []
std = ["base16/std", "contract-ffi/std"]

[dependencies]
base16 = { version = "0.2.1", default-features = false }
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
