[package]
name = "args-multi"
version = "0.1.0"
authors = ["Joe Sacher <joe@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract-ffi/std" ]

[dependencies]
contract-ffi = { path = "../../../../execution-engine/contract-ffi", package = "casperlabs-contract-ffi" }
