[genesis]

# Human readable name for convenience; the genesis_hash is the true identifier.
# The name influences the genesis hash by contributing to the seeding of the pseudo-
# random number generator used in execution engine for computing genesis post-state.
name = "casperlabs"

# Timestamp for the genesis block, also used in seeding the pseudo-random number
# generator used in execution engine for computing genesis post-state.
timestamp = 0

# Later will be replaced by semver.
protocol-version = 1

# Path (absolute, or relative to the manifest) to the file containing wasm bytecode for installing the mint system contract.
mint-code-path = "mint_install.wasm"

# Path (absolute, or relative to the manifest) to the file containing wasm bytecode for installing the mint system contract.
pos-code-path = "pos_install.wasm"

# Path (absolute, or relative to the manifest) to the CSV file containing initial account balances and bonds.
initial-accounts-path = "accounts.csv"

[wasm-costs]
# Default opcode cost
regular = 1
# Div operations multiplier.
div-multiplier = 1
# Mul operations multiplier.
mul-multiplier = 1
# Memory (load/store) operations multiplier.
mem-multiplier = 1
# Amount of free memory (in 64kb pages) each contract can use for stack.
mem-initial-pages = 1
# Grow memory cost, per page (64kb)
mem-grow-per-page = 1
# Memory copy cost, per byte
mem-copy-per-byte = 1
# Max stack height (native WebAssembly stack limiter)
max-stack-height = 1
# Cost of wasm opcode is calculated as TABLE_ENTRY_COST * `opcodes_mul` / `opcodes_div`
opcodes-multiplier = 1
opcodes-divisor = 1
