[package]
name = "list-known-urefs-call"
version = "0.1.0"
authors = ["Mateusz Górski <mateusz@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
contract-ffi = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }
