[package]
name = "bonding"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = []
std = ["contract-ffi/std", "contracts-common/std"]

[dependencies]
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
contracts-common = { path = "../../contracts-common", package = "casperlabs-contracts-common" }
