[grpc]
host = "qndmvgrDpojz6onyurcmiwbcqty3Ff1w7v1k0ummm04bduy1nyGsKquvfhkwxwbbiW"
socket = "/P:P:t:p:e:H:o:8:u"
port-external = -1
port-internal = 2054361139
[server]
init-sync-max-block-count = 1975953512
dynamic-host-address = true
sync-min-block-count-to-check-branching-factor = 8002570
download-retry-backoff-factor = 5.035920767041142
max-num-of-connections = 2147483647
approval-poll-interval = "2035438979milliseconds"
sync-max-possible-depth = 44453139
relay-saturation = -67969702
sync-max-branching-factor = 6.020296086714315
download-retry-initial-backoff-period = "515777073milliseconds"
relay-block-chunk-consumer-timeout = "2145644917milliseconds"
data-dir = "/e:i:g:4:E:j:y:m:w:c:b:i:q:Q:k:e:q:n:a:f:v:g:s:f:J:F:S"
max-message-size = -2147483648
http-port = -132399467
init-sync-memoize-nodes = true
init-sync-min-successful = 1665444749
init-sync-skip-failed-nodes = true
default-timeout = -2004422886
download-max-retries = 1371887663
sync-max-depth-ancestors-request = 419019085
relay-factor = 0
port = 1595351474
store-type = "lmdb"
kademlia-port = 0
use-gossiping = true
relay-max-parallel-blocks = 1293949879
clean-block-storage = true
no-upnp = true
init-sync-max-nodes = 0
init-sync-round-period = "1988408324milliseconds"
download-max-parallel-blocks = -1420243294
approval-relay-factor = 1
chunk-size = -1
[influx]
hostname = "qtg8mUTdax1ch7ueog7vkn6tpkv8GhtcyelztCgpvxP9Q3eHefxb5bwpc8dkflep6npvBtzswtsgt"
port = 0
database = "tqsp1gigCOzwzZuKxuwdrmknbcmQcdm6ttpByrgypEnytvdpeqgltVgjhmonacnoxjAuv2xurgok"
protocol = "qlciRyulZuhemyf4r9dUbbzdimhrqpnqGseg2g1auDMxiqchucyyp4jcsb8juypppB6xckkpjpmm2rRh5Oba0s3opR"
[casper]
minimum-bond = -2685603993776483770
maximum-bond = 0
approve-genesis-duration = "1968029869milliseconds"
auto-propose-max-interval = "21696725milliseconds"
num-validators = -718467160
shard-id = "kh1ogulbRq"
ignore-deploy-signature = true
approve-genesis-interval = "1764122117milliseconds"
standalone = true
approve-genesis = true
auto-propose-max-count = -1
wallets-file = "/t:9:n:5:j:i:D:n:0:p:e:b:u:i:0"
bonds-file = "/y:d:1:k:p:a:i:9:l:e:d:j:s:F:m:a:q:g"
required-sigs = 1
validator-sig-algorithm = "kcoqvdby8wfnneamz7AnaBuelyat26add"
known-validators-file = "/s:i:p:g:k:s:k:X:c:w:E:s"
has-faucet = true
auto-propose-enabled = true
auto-propose-check-interval = "1143612646milliseconds"
[lmdb]
block-store-size = -7351768579688900125
max-dbs = 2147483647
max-readers = -203020729
use-tls = true
[tls]
certificate = "/d:7:w:6:d:k:r:u:h:u:L:k:f:N:j:s:D:j:e:m:o:e:b:a:t:x:m:h:o:e"
key = "/p:c:c:e:q:h:d:z:j:g:n:y:9:f:k:8:y:5:t:d:v"
secure-random-non-blocking = true
[blockstorage]
latest-messages-log-max-size-factor = -314341099
[metrics]
prometheus = true
zipkin = true
sigar = true
influx = true
