[package]
name = "combined-contracts-define"
version = "0.1.0"
authors = ["Srinivas Reddy Thatiparthy <srini@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[dependencies]
contract-ffi = {package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }
