[package]
name = "payment-purse"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>",
           "Srinivas Reddy Thatiparthy <srini@casperlabs.io>"]
edition = "2018"

[lib]
name = "test_payment_purse"
crate-type = ["cdylib"]

[features]
default = []
std = ["contract-ffi/std", "contracts-common/std"]

[dependencies]
contract-ffi = { package = "casperlabs-contract-ffi", path = "../../../execution-engine/contract-ffi" }
contracts-common = { path = "../../../execution-engine/contracts/contracts-common", package = "casperlabs-contracts-common" }
