[package]
name = "finalize-payment"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>",
           "Srinivas Reddy Thatiparthy <srini@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }
